default_language_version:
  python: python3.8

minimum_pre_commit_version: "2.10.0"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
        args:
          - "--unsafe"  # needed for parsing CFN
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.26.0
    hooks:
      - id: markdownlint
  - repo: local
    hooks:
      - id: ssm-dox-check
        name: ssm-dox-check
        entry: .venv/bin/ssm-dox check ./dox ./shared_ssm_docs
        language: python
        pass_filenames: false
        types:
          - text
        exclude_types:
          - markdown
