Parameters:
  BucketName:
    Default: Undefined
    Description: Name of the Bucket.
    Type: String
  VersioningStatus:
    AllowedValues:
      - Enabled
      - Suspended
    Default: Enabled
    Description: The status of VersioningConfiguration for the Bucket.
    Type: String


Conditions:
  BucketNameProvided:
    !Not [ !Equals [ !Ref BucketName, Undefined ] ]


Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !If
        - BucketNameProvided
        - !Ref BucketName
        - !Ref AWS::NoValue
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      VersioningConfiguration:
        Status: !Ref VersioningStatus
  BucketPolicyPublic:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Principal: "*"
            Resource:
              - !Sub ${Bucket.Arn}/*


Outputs:
  Bucket:
    Description: Name of the Bucket
    Value: !Ref Bucket
  BucketArn:
    Description: ARN of the Bucket
    Value: !GetAtt Bucket.Arn
  BucketDomainName:
    Description: DNS name of the Bucket
    Value: !GetAtt Bucket.DomainName
  BucketRegionalDomainName:
    Description: DNS name with region of the Bucket
    Value: !GetAtt Bucket.RegionalDomainName
