namespace: ${namespace}
cfngin_bucket: ""

sys_path: ./

stacks:
  - name: bucket
    template_path: ./templates/s3_bucket_public.yml
    variables:
      BucketName: ${default bucket_name::Undefined}
      VersioningStatus: ${default versioning::Enabled}

pre_destroy:
  - path: runway.hooks.cleanup_s3.purge_bucket
    required: true
    args:
      bucket_name: ${cfn ${namespace}-bucket.Bucket::default=Undefined}
