name: lint

on:
  push:

jobs:
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          path: .venv
      - name: Install Poetry
        uses: Gr1N/setup-poetry@v4
      - name: Install Dependencies
        run: poetry install -vv
      - name: Run Linters
        run: make lint
  lint-shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Shell Linters
        run: make lint-shell
