name: lint

on:
  push:

jobs:
  lint-powershell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run PowerShell Linters
        run: make lint-powershell
  lint-shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Shell Linters
        run: make lint-shell
